// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id           int64          `db:"id"`            // 用户id
		Name         string         `db:"name"`          // 用户昵称
		Avatar       sql.NullString `db:"avatar"`        // 用户头像
		Sex          sql.NullInt64  `db:"sex"`           // 性别 1为男性，2为女性
		OpenId       sql.NullString `db:"open_id"`       // 微信openid用户标识
		ActiveStatus sql.NullInt64  `db:"active_status"` // 上下线状态 1在线 2离线
		LastOptTime  sql.NullTime   `db:"last_opt_time"` // 最后上下线时间
		IpInfo       sql.NullString `db:"ip_info"`       // IP信息
		ItemId       sql.NullInt64  `db:"item_id"`       // 佩戴的徽章id
		Status       sql.NullInt64  `db:"status"`        // 用户状态 0正常 1拉黑
		CreateTime   sql.NullTime   `db:"create_time"`   // 创建时间
		UpdateTime   sql.NullTime   `db:"update_time"`   // 修改时间
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Avatar, data.Sex, data.OpenId, data.ActiveStatus, data.LastOptTime, data.IpInfo, data.ItemId, data.Status)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Avatar, data.Sex, data.OpenId, data.ActiveStatus, data.LastOptTime, data.IpInfo, data.ItemId, data.Status, data.Id)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
