// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type UserLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type UserRegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Code     string `json:"code"`
}
