// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type GetUserInfoResp struct {
	Id         int64  `json:"id"`
	Mobile     string `json:"mobile"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"createTime"`
}

type ResetPasswordReq struct {
	Mobile      string `json:"mobile"`
	NewPassword string `json:"newPassword"`
	Code        string `json:"code"`
}

type SendSmsReq struct {
	Mobile string `json:"mobile"`
	Scene  string `json:"scene"` // register-注册 reset-重置密码
}

type SendSmsResp struct {
	Code string `json:"code"` // 测试环境可返回验证码
}

type UpdateUserReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UploadAvatarReq struct {
	File string `form:"file,optional"`
}

type UploadAvatarResp struct {
	Url string `json:"url"`
}

type User struct {
	Id         int64  `json:"id"`
	Mobile     string `json:"mobile"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"createTime"`
}

type UserLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserInfo     User   `json:"userInfo"`
}

type UserRegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type UserRegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
