// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	blackFieldNames          = builder.RawFieldNames(&Black{})
	blackRows                = strings.Join(blackFieldNames, ",")
	blackRowsExpectAutoSet   = strings.Join(stringx.Remove(blackFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	blackRowsWithPlaceHolder = strings.Join(stringx.Remove(blackFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	blackModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Black) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*Black, error)
		Update(ctx context.Context, session sqlx.Session, data *Black) (sql.Result, error)
		UpdateAndSql(ctx context.Context, session sqlx.Session, data *Black, andSql string) (sql.Result, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultBlackModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Black struct {
		Id         int64     `db:"id"`          // 拉黑记录ID
		Type       int64     `db:"type"`        // 拉黑目标类型 1.ip 2.uid
		Target     string    `db:"target"`      // 拉黑目标
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 修改时间
	}
)

func newBlackModel(conn sqlx.SqlConn) *defaultBlackModel {
	return &defaultBlackModel{
		conn:  conn,
		table: "`black`",
	}
}

func (m *defaultBlackModel) Insert(ctx context.Context, session sqlx.Session, data *Black) (sql.Result, error) {
	//data.DeleteTime = time.Unix(0,0)

	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, blackRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Type, data.Target)
	}
	return m.conn.ExecCtx(ctx, query, data.Type, data.Target)
}

func (m *defaultBlackModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*Black, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", blackRows, m.table)
	var resp Black
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBlackModel) Update(ctx context.Context, session sqlx.Session, data *Black) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, blackRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Type, data.Target, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Type, data.Target, data.Id)
}

func (m *defaultBlackModel) UpdateAndSql(ctx context.Context, session sqlx.Session, data *Black, andSql string) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ? %s", m.table, blackRowsWithPlaceHolder, andSql)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Type, data.Target, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Type, data.Target, data.Id)
}

func (m *defaultBlackModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultBlackModel) tableName() string {
	return m.table
}
