// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"time"

	"github.com/Masterminds/squirrel"
	"github.com/pkg/errors"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	itemConfigsFieldNames          = builder.RawFieldNames(&ItemConfigs{})
	itemConfigsRows                = strings.Join(itemConfigsFieldNames, ",")
	itemConfigsRowsExpectAutoSet   = strings.Join(stringx.Remove(itemConfigsFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	itemConfigsRowsWithPlaceHolder = strings.Join(stringx.Remove(itemConfigsFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	itemConfigsModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *ItemConfigs) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ItemConfigs, error)
		Update(ctx context.Context, session sqlx.Session, data *ItemConfigs) (sql.Result, error)
		Trans(ctx context.Context, fn func(context context.Context, session sqlx.Session) error) error
		SelectBuilder() squirrel.SelectBuilder
		FindSum(ctx context.Context, sumBuilder squirrel.SelectBuilder, field string) (float64, error)
		FindCount(ctx context.Context, countBuilder squirrel.SelectBuilder, field string) (int64, error)
		FindAll(ctx context.Context, rowBuilder squirrel.SelectBuilder, orderBy string) ([]*ItemConfigs, error)
		FindPageListByPage(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ItemConfigs, error)
		FindPageListByPageWithTotal(ctx context.Context, rowBuilder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ItemConfigs, int64, error)
		FindPageListByIdDESC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ItemConfigs, error)
		FindPageListByIdASC(ctx context.Context, rowBuilder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ItemConfigs, error)
		Delete(ctx context.Context, session sqlx.Session, id uint64) error
	}

	defaultItemConfigsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ItemConfigs struct {
		Id        uint64    `db:"id"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
		DeletedAt time.Time `db:"deleted_at"`
		Type      int64     `db:"type"`     // 物品类型 1改名卡 2徽章
		Img       string    `db:"img"`      // 物品图片
		Describe  string    `db:"describe"` // 物品功能描述
	}
)

func newItemConfigsModel(conn sqlx.SqlConn) *defaultItemConfigsModel {
	return &defaultItemConfigsModel{
		conn:  conn,
		table: "`item_configs`",
	}
}

func (m *defaultItemConfigsModel) Insert(ctx context.Context, session sqlx.Session, data *ItemConfigs) (sql.Result, error) {
	data.DeletedAt = time.Time{}

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, itemConfigsRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.DeletedAt, data.Type, data.Img, data.Describe)
	}
	return m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Type, data.Img, data.Describe)
}

func (m *defaultItemConfigsModel) FindOne(ctx context.Context, id uint64) (*ItemConfigs, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  and deleted_at = ? limit 1", itemConfigsRows, m.table)
	var resp ItemConfigs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id, time.Time{})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultItemConfigsModel) Update(ctx context.Context, session sqlx.Session, data *ItemConfigs) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, itemConfigsRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.DeletedAt, data.Type, data.Img, data.Describe, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.DeletedAt, data.Type, data.Img, data.Describe, data.Id)
}

func (m *defaultItemConfigsModel) FindSum(ctx context.Context, builder squirrel.SelectBuilder, field string) (float64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindSum Least One Field"), "FindSum Least One Field")
	}

	builder = builder.Columns("IFNULL(SUM(" + field + "),0)")

	query, values, err := builder.Where("deleted_at = ?", time.Time{}).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultItemConfigsModel) FindCount(ctx context.Context, builder squirrel.SelectBuilder, field string) (int64, error) {

	if len(field) == 0 {
		return 0, errors.Wrapf(errors.New("FindCount Least One Field"), "FindCount Least One Field")
	}

	builder = builder.Columns("COUNT(" + field + ")")

	query, values, err := builder.Where("deleted_at = ?", time.Time{}).ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultItemConfigsModel) FindAll(ctx context.Context, builder squirrel.SelectBuilder, orderBy string) ([]*ItemConfigs, error) {

	builder = builder.Columns(itemConfigsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	query, values, err := builder.Where("deleted_at = ?", time.Time{}).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ItemConfigs

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultItemConfigsModel) FindPageListByPage(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ItemConfigs, error) {

	builder = builder.Columns(itemConfigsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("deleted_at = ?", time.Time{}).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ItemConfigs

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultItemConfigsModel) FindPageListByPageWithTotal(ctx context.Context, builder squirrel.SelectBuilder, page, pageSize int64, orderBy string) ([]*ItemConfigs, int64, error) {

	total, err := m.FindCount(ctx, builder, "id")
	if err != nil {
		return nil, 0, err
	}

	builder = builder.Columns(itemConfigsRows)

	if orderBy == "" {
		builder = builder.OrderBy("id DESC")
	} else {
		builder = builder.OrderBy(orderBy)
	}

	if page < 1 {
		page = 1
	}
	offset := (page - 1) * pageSize

	query, values, err := builder.Where("deleted_at = ?", time.Time{}).Offset(uint64(offset)).Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, total, err
	}

	var resp []*ItemConfigs

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, total, nil
	default:
		return nil, total, err
	}
}

func (m *defaultItemConfigsModel) FindPageListByIdDESC(ctx context.Context, builder squirrel.SelectBuilder, preMinId, pageSize int64) ([]*ItemConfigs, error) {

	builder = builder.Columns(itemConfigsRows)

	if preMinId > 0 {
		builder = builder.Where(" id < ? ", preMinId)
	}

	query, values, err := builder.Where("deleted_at = ?", time.Time{}).OrderBy("id DESC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ItemConfigs

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultItemConfigsModel) FindPageListByIdASC(ctx context.Context, builder squirrel.SelectBuilder, preMaxId, pageSize int64) ([]*ItemConfigs, error) {

	builder = builder.Columns(itemConfigsRows)

	if preMaxId > 0 {
		builder = builder.Where(" id > ? ", preMaxId)
	}

	query, values, err := builder.Where("deleted_a = ?", 1).OrderBy("id ASC").Limit(uint64(pageSize)).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*ItemConfigs

	err = m.conn.QueryRowsCtx(ctx, &resp, query, values...)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultItemConfigsModel) Trans(ctx context.Context, fn func(ctx context.Context, session sqlx.Session) error) error {

	return m.conn.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})

}

func (m *defaultItemConfigsModel) SelectBuilder() squirrel.SelectBuilder {
	return squirrel.Select().From(m.table)
}
func (m *defaultItemConfigsModel) Delete(ctx context.Context, session sqlx.Session, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultItemConfigsModel) tableName() string {
	return m.table
}
