// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageFieldNames          = builder.RawFieldNames(&Message{})
	messageRows                = strings.Join(messageFieldNames, ",")
	messageRowsExpectAutoSet   = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	messageRowsWithPlaceHolder = strings.Join(stringx.Remove(messageFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheMallchatgoMessageIdPrefix = "cache:mallchatgo:message:id:"
)

type (
	messageModel interface {
		Insert(ctx context.Context, data *Message) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Message, error)
		Update(ctx context.Context, data *Message) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultMessageModel struct {
		sqlc.CachedConn
		table string
	}

	Message struct {
		Id         uint64 `db:"id"`          // 消息ID
		SenderId   uint64 `db:"sender_id"`   // 发送者ID
		ReceiverId uint64 `db:"receiver_id"` // 接收者ID
		Content    string `db:"content"`     // 消息内容
		Type       int64  `db:"type"`        // 消息类型 1:文本 2:图片 3:语音 4:视频
		Status     int64  `db:"status"`      // 消息状态 1:未读 2:已读
		CreateTime int64  `db:"create_time"` // 创建时间
		UpdateTime int64  `db:"update_time"` // 更新时间
	}
)

func newMessageModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultMessageModel {
	return &defaultMessageModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`message`",
	}
}

func (m *defaultMessageModel) Delete(ctx context.Context, id uint64) error {
	mallchatgoMessageIdKey := fmt.Sprintf("%s%v", cacheMallchatgoMessageIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, mallchatgoMessageIdKey)
	return err
}

func (m *defaultMessageModel) FindOne(ctx context.Context, id uint64) (*Message, error) {
	mallchatgoMessageIdKey := fmt.Sprintf("%s%v", cacheMallchatgoMessageIdPrefix, id)
	var resp Message
	err := m.QueryRowCtx(ctx, &resp, mallchatgoMessageIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMessageModel) Insert(ctx context.Context, data *Message) (sql.Result, error) {
	mallchatgoMessageIdKey := fmt.Sprintf("%s%v", cacheMallchatgoMessageIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, messageRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.Content, data.Type, data.Status)
	}, mallchatgoMessageIdKey)
	return ret, err
}

func (m *defaultMessageModel) Update(ctx context.Context, data *Message) error {
	mallchatgoMessageIdKey := fmt.Sprintf("%s%v", cacheMallchatgoMessageIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SenderId, data.ReceiverId, data.Content, data.Type, data.Status, data.Id)
	}, mallchatgoMessageIdKey)
	return err
}

func (m *defaultMessageModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheMallchatgoMessageIdPrefix, primary)
}

func (m *defaultMessageModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultMessageModel) tableName() string {
	return m.table
}
