// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roleFieldNames          = builder.RawFieldNames(&Role{})
	roleRows                = strings.Join(roleFieldNames, ",")
	roleRowsExpectAutoSet   = strings.Join(stringx.Remove(roleFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	roleRowsWithPlaceHolder = strings.Join(stringx.Remove(roleFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	roleModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *Role) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*Role, error)
		Update(ctx context.Context, session sqlx.Session, data *Role) (sql.Result, error)
		UpdateAndSql(ctx context.Context, session sqlx.Session, data *Role, andSql string) (sql.Result, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Role struct {
		Id         int64     `db:"id"`          // 角色ID
		Name       string    `db:"name"`        // 角色名称
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 修改时间
	}
)

func newRoleModel(conn sqlx.SqlConn) *defaultRoleModel {
	return &defaultRoleModel{
		conn:  conn,
		table: "`role`",
	}
}

func (m *defaultRoleModel) Insert(ctx context.Context, session sqlx.Session, data *Role) (sql.Result, error) {
	//data.DeleteTime = time.Unix(0,0)

	query := fmt.Sprintf("insert into %s (%s) values (?)", m.table, roleRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Name)
	}
	return m.conn.ExecCtx(ctx, query, data.Name)
}

func (m *defaultRoleModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*Role, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", roleRows, m.table)
	var resp Role
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleModel) Update(ctx context.Context, session sqlx.Session, data *Role) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, roleRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Name, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Name, data.Id)
}

func (m *defaultRoleModel) UpdateAndSql(ctx context.Context, session sqlx.Session, data *Role, andSql string) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ? %s", m.table, roleRowsWithPlaceHolder, andSql)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Name, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Name, data.Id)
}

func (m *defaultRoleModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRoleModel) tableName() string {
	return m.table
}
