// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFriendFieldNames          = builder.RawFieldNames(&UserFriend{})
	userFriendRows                = strings.Join(userFriendFieldNames, ",")
	userFriendRowsExpectAutoSet   = strings.Join(stringx.Remove(userFriendFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userFriendRowsWithPlaceHolder = strings.Join(stringx.Remove(userFriendFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	userFriendModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserFriend) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*UserFriend, error)
		Update(ctx context.Context, session sqlx.Session, data *UserFriend) (sql.Result, error)
		UpdateAndSql(ctx context.Context, session sqlx.Session, data *UserFriend, andSql string) (sql.Result, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultUserFriendModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserFriend struct {
		Id           int64     `db:"id"`            // 联系人ID
		Uid          int64     `db:"uid"`           // 用户UID
		FriendUid    int64     `db:"friend_uid"`    // 好友UID
		DeleteStatus int64     `db:"delete_status"` // 逻辑删除(0-正常,1-删除)
		CreateTime   time.Time `db:"create_time"`   // 创建时间
		UpdateTime   time.Time `db:"update_time"`   // 修改时间
	}
)

func newUserFriendModel(conn sqlx.SqlConn) *defaultUserFriendModel {
	return &defaultUserFriendModel{
		conn:  conn,
		table: "`user_friend`",
	}
}

func (m *defaultUserFriendModel) Insert(ctx context.Context, session sqlx.Session, data *UserFriend) (sql.Result, error) {
	//data.DeleteTime = time.Unix(0,0)

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, userFriendRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Uid, data.FriendUid, data.DeleteStatus)
	}
	return m.conn.ExecCtx(ctx, query, data.Uid, data.FriendUid, data.DeleteStatus)
}

func (m *defaultUserFriendModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*UserFriend, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", userFriendRows, m.table)
	var resp UserFriend
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserFriendModel) Update(ctx context.Context, session sqlx.Session, data *UserFriend) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userFriendRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Uid, data.FriendUid, data.DeleteStatus, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Uid, data.FriendUid, data.DeleteStatus, data.Id)
}

func (m *defaultUserFriendModel) UpdateAndSql(ctx context.Context, session sqlx.Session, data *UserFriend, andSql string) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ? %s", m.table, userFriendRowsWithPlaceHolder, andSql)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Uid, data.FriendUid, data.DeleteStatus, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Uid, data.FriendUid, data.DeleteStatus, data.Id)
}

func (m *defaultUserFriendModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserFriendModel) tableName() string {
	return m.table
}
