// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userBackpackFieldNames          = builder.RawFieldNames(&UserBackpack{})
	userBackpackRows                = strings.Join(userBackpackFieldNames, ",")
	userBackpackRowsExpectAutoSet   = strings.Join(stringx.Remove(userBackpackFieldNames, "`id`", "`create_time`", "`update_time`"), ",")
	userBackpackRowsWithPlaceHolder = strings.Join(stringx.Remove(userBackpackFieldNames, "`id`", "`create_time`", "`update_time`"), "=?,") + "=?"
)

type (
	userBackpackModel interface {
		Insert(ctx context.Context, session sqlx.Session, data *UserBackpack) (sql.Result, error)
		FindOne(ctx context.Context, session sqlx.Session, id int64) (*UserBackpack, error)
		Update(ctx context.Context, session sqlx.Session, data *UserBackpack) (sql.Result, error)
		UpdateAndSql(ctx context.Context, session sqlx.Session, data *UserBackpack, andSql string) (sql.Result, error)

		Delete(ctx context.Context, session sqlx.Session, id int64) error
	}

	defaultUserBackpackModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserBackpack struct {
		Id         int64          `db:"id"`          // 背包ID
		Uid        int64          `db:"uid"`         // 用户UID
		ItemId     int64          `db:"item_id"`     // 物品ID
		Status     int64          `db:"status"`      // 使用状态 0.未失效 1失效
		Idempotent sql.NullString `db:"idempotent"`  // 幂等号
		CreateTime time.Time      `db:"create_time"` // 创建时间
		UpdateTime time.Time      `db:"update_time"` // 修改时间
	}
)

func newUserBackpackModel(conn sqlx.SqlConn) *defaultUserBackpackModel {
	return &defaultUserBackpackModel{
		conn:  conn,
		table: "`user_backpack`",
	}
}

func (m *defaultUserBackpackModel) Insert(ctx context.Context, session sqlx.Session, data *UserBackpack) (sql.Result, error) {
	//data.DeleteTime = time.Unix(0,0)

	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, userBackpackRowsExpectAutoSet)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Uid, data.ItemId, data.Status, data.Idempotent)
	}
	return m.conn.ExecCtx(ctx, query, data.Uid, data.ItemId, data.Status, data.Idempotent)
}

func (m *defaultUserBackpackModel) FindOne(ctx context.Context, session sqlx.Session, id int64) (*UserBackpack, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ?  limit 1", userBackpackRows, m.table)
	var resp UserBackpack
	var err error
	if session != nil {
		err = session.QueryRowCtx(ctx, &resp, query, id)
	} else {
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserBackpackModel) Update(ctx context.Context, session sqlx.Session, data *UserBackpack) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userBackpackRowsWithPlaceHolder)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Uid, data.ItemId, data.Status, data.Idempotent, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Uid, data.ItemId, data.Status, data.Idempotent, data.Id)
}

func (m *defaultUserBackpackModel) UpdateAndSql(ctx context.Context, session sqlx.Session, data *UserBackpack, andSql string) (sql.Result, error) {
	query := fmt.Sprintf("update %s set %s where `id` = ? %s", m.table, userBackpackRowsWithPlaceHolder, andSql)
	if session != nil {
		return session.ExecCtx(ctx, query, data.Uid, data.ItemId, data.Status, data.Idempotent, data.Id)
	}
	return m.conn.ExecCtx(ctx, query, data.Uid, data.ItemId, data.Status, data.Idempotent, data.Id)
}

func (m *defaultUserBackpackModel) Delete(ctx context.Context, session sqlx.Session, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	if session != nil {
		_, err := session.ExecCtx(ctx, query, id)
		return err
	}
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserBackpackModel) tableName() string {
	return m.table
}
