// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type CreateGroupReq struct {
	GroupName string `json:"groupName"` // 群组名称
}

type CreateGroupResp struct {
	GroupId int64 `json:"groupId"` // 群组ID
}

type GetMessageListReq struct {
	ReceiverId    int64 `json:"receiverId"`
	LastMessageId int64 `json:"lastMessageId,optional"` // 上一页最后一条消息ID
	Size          int32 `json:"size,optional,default=20"`
}

type GetMessageListResp struct {
	Messages []Message `json:"messages"`
	HasMore  bool      `json:"hasMore"`
}

type GetUserInfoResp struct {
	Id         int64  `json:"id"`
	Mobile     string `json:"mobile"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"createTime"`
}

type JoinGroupReq struct {
	GroupId int64 `json:"groupId"` // 群组ID
	UserId  int64 `json:"userId"`  // 用户ID
}

type JoinGroupResp struct {
	Message string `json:"message"` // 加入群组成功消息
}

type Message struct {
	Id         int64  `json:"id"`
	SenderId   int64  `json:"senderId"`
	ReceiverId int64  `json:"receiverId"`
	Content    string `json:"content"`
	Type       int32  `json:"type"` // 1:文本 2:图片 3:语音 4:视频
	CreateTime int64  `json:"createTime"`
}

type ResetPasswordReq struct {
	Mobile      string `json:"mobile"`
	NewPassword string `json:"newPassword"`
	Code        string `json:"code"`
}

type SendMessageReq struct {
	ReceiverId int64  `json:"receiverId"`
	Content    string `json:"content"`
	Type       int32  `json:"type"`
	SenderId   int64  `json:"senderId"`
}

type SendMessageResp struct {
	MessageId int64 `json:"messageId"`
}

type SendSmsReq struct {
	Mobile string `json:"mobile"`
	Scene  string `json:"scene"` // register-注册 reset-重置密码
}

type SendSmsResp struct {
	Code string `json:"code"` // 测试环境可返回验证码
}

type UpdateUserReq struct {
	Nickname string `json:"nickname,optional"`
	Avatar   string `json:"avatar,optional"`
}

type UploadAvatarReq struct {
	File string `form:"file,optional"`
}

type UploadAvatarResp struct {
	Url string `json:"url"`
}

type User struct {
	Id         int64  `json:"id"`
	Mobile     string `json:"mobile"`
	Nickname   string `json:"nickname"`
	Avatar     string `json:"avatar"`
	CreateTime int64  `json:"createTime"`
}

type UserLoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
	UserInfo     User   `json:"userInfo"`
}

type UserRegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
	Code     string `json:"code"`
}

type UserRegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
