// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type UserInfoReq struct {
	UserId int64 `form:"user_id"`
}

type UserInfoResp struct {
	Id           uint   `json:"id"`
	Name         string `json:"name"`
	Mobile       string `json:"mobile"`
	Avatar       string `json:"avatar"`
	Sex          int    `json:"sex"`
	ActiveStatus int    `json:"active_status"`
	ItemID       int64  `json:"item_id"`
	Status       int    `json:"status"`
}
