// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	login "mallchat-go/app/user/internal/handler/login"
	user "mallchat-go/app/user/internal/handler/user"
	"mallchat-go/app/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: login.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: login.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/password/reset",
				Handler: user.ResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sms/send",
				Handler: user.SendSmsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/capi/user"),
	)

	// 需要认证的路由
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/avatar/upload",
				Handler: user.UploadAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: user.GetUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update",
				Handler: user.UpdateUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/capi/user"),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
