// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	user "mallchat-go/app/internal/handler/user"
	"mallchat-go/app/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					// 佩戴徽章
					Method:  http.MethodPut,
					Path:    "/badge",
					Handler: user.WearingBadgeHandler(serverCtx),
				},
				{
					// 修改用户名
					Method:  http.MethodPut,
					Path:    "/name",
					Handler: user.ModifyNameHandler(serverCtx),
				},
				{
					// 用户详情
					Method:  http.MethodGet,
					Path:    "/userInfo",
					Handler: user.UserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/capi/user"),
	)
}
